# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 16:15
from __future__ import unicode_literals

from django.db import migrations



def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group, __ = Group.objects.get_or_create(name=REDHOUSE_ADMIN_PANEL_ACCESS)
    group.save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=REDHOUSE_ADMIN_PANEL_ACCESS).delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
